version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - minio
    env_file:
      - .env
    environment:
      - MINIO_ENDPOINT=http://minio:9000  # Explicitly use http://

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - .env
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    entrypoint: [ "/bin/sh", "-c", "minio server --console-address ':9001' /data" ]

volumes:
  mongodb_data:
  minio_data:
