name: CI Pipeline

on:
  push:
    branches:
      - arzan03-ci-patch-1
  pull_request:
    branches:
      - arzan03-ci-patch-1

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: docker version

      - name: Clean up previous resources
        run: docker system prune -f

      - name: Create local Docker network
        run: docker network create github_network || true

      - name: Start MinIO
        run: |
          docker run -d --name minio --network github_network \
            -p 9000:9000 -p 9001:9001 \
            -e "MINIO_ROOT_USER=minioadmin" \
            -e "MINIO_ROOT_PASSWORD=minioadmin" \
            minio/minio server --console-address ":9001" /data

      - name: Verify MinIO is running
        run: |
          sleep 5  # Give MinIO time to start
          docker ps -a

      - name: Start MongoDB
        run: |
          docker run -d --name mongodb --network github_network \
            -p 27017:27017 \
            mongo:latest

      - name: Verify MongoDB is running
        run: |
          sleep 5  # Give MongoDB time to start
          docker ps -a

      - name: Run Tests
        run: |
          echo "Running tests..."
          # Add your test command here

      - name: Cleanup
        if: always()
        run: |
          docker stop minio mongodb || true
          docker rm minio mongodb || true
