name: CI Pipeline

on:
  push:
    branches:
      - arzan03-ci-patch-1
  pull_request:
    branches:
      - arzan03-ci-patch-1

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping:1})'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Start MinIO
        run: |
          docker run -d --name minio \
            -p 9000:9000 -p 9001:9001 \
            -e "MINIO_ROOT_USER=minioadmin" \
            -e "MINIO_ROOT_PASSWORD=minioadmin" \
            minio/minio server /data

      - name: Wait for MinIO to be ready
        run: |
          sleep 10

      - name: Create MinIO bucket
        run: |
          docker run --rm --network host minio/mc alias set local http://localhost:9000 minioadmin minioadmin
          docker run --rm --network host minio/mc mb local/secure-share

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build application
        run: |
          go build -o app ./cmd

      - name: Start application
        run: |
          ./app &
          sleep 5

      - name: Run tests
        run: |
          go test -v ./tests
